### PR TITLE
add stuff to list.txt

### PR DESCRIPTION
**Pull request by pazza08223**
this makes it work with the all bookmark, bookmark.

### CODE REVIEW

**Review by username-pass — CHANGES_REQUESTED** [review]
remove the.js in the list, and also remove all-bookmarklets.js and all-depbookmarklets.js (all-bookmarklets is the window that allows the selection, and all-depbookmarklets is there for compatibility reasons

**Comment by pazza08223** [comment]
ok

**Comment by pazza08223** [comment]
done

**Review by username-pass — CHANGES_REQUESTED** [review]
add a space before every element that is the deliminator for the list(ex: " notepad")

**Review by username-pass — APPROVED** [review]

**Pull request merged**
